export default {
  table_data: {
    headers: [
      { title: "No", key: "no" },
      { title: "NOP", key: "taxObjectNumber", sortable: false },
      {
        title: "Pemilik",
        key: "taxPayerName",
        sortable: false,
        minWidth: "300px",
      },
      {
        title: "Kelurahan",
        key: "village",
        sortable: false,
        minWidth: "150px",
      },
      { title: "RT", key: "rt", sortable: false },
      {
        title: "Luas Bangunan Lama",
        key: "luasBgnLama",
        sortable: false,
        minWidth: "150px",
      },
      {
        title: "Luas Bangunan Baru",
        key: "luasBgn",
        sortable: false,
        minWidth: "150px",
      },
      { title: "Jumlah Lantai", key: "floorCount", sortable: false },
      {
        title: "Tipe Bangunan",
        key: "buildingType",
        sortable: false,
        minWidth: "200px",
      },
      { title: "Tipe Lantai", key: "buildingFloorType", sortable: false },
      {
        title: "Tipe Dinding",
        key: "buildingWall",
        sortable: false,
        minWidth: "150px",
      },
      { title: "Tipe Atap", key: "roofType", sortable: false },
      {
        title: "Tipe Konstruksi",
        key: "buildingConstruction",
        sortable: false,
      },
      { title: "Status", key: "update", sortable: false, minWidth: "150px" },
      { title: "Actions", key: "action", sortable: false, minWidth: "150px" },
    ],
  },
  table_collection: {
    headers: [
      { title: "No", key: "no", sortable: false },
      { title: "Province", key: "province", sortable: false },
      { title: "City", key: "city", sortable: false },
      { title: "Kecamatan", key: "district", sortable: false },
      { title: "Kelurahan", key: "village", sortable: false },
      { title: "Alamat", key: "address", sortable: false },
      { title: "Jumlah Lantai", key: "floorCount", sortable: false },
      { title: "NOP", key: "taxObjectNumber", sortable: false },
      { title: "NOP BARU", key: "newTaxObjectNumber", sortable: false },
      { title: "Status", key: "buildingUpdate", sortable: false },
    ],
  },
  detail_item: {
    identitas: {
      id: "ID",
      uuid_bgn: "UUID Bangunan",
      nopBgn: "NOP Bangunan",
      taxObjectNumber: "Nomor Objek Pajak",
      taxObjectCode_1: "Kode Objek Pajak 1",
      ownerType: "Jenis Pemilik",
    },
    wajibPajak: {
      taxPayerCode: "Kode Wajib Pajak",
      taxPayerName: "Nama Wajib Pajak",
      taxStatus: "Status Pajak",
      update: "Status Update",
    },
    metadata: {
      createdAt: "Tanggal Dibuat",
      updatedAt: "Tanggal Update",
      dateUpdt: "Tanggal Diperbarui (Sumber)",
      imageUrls: "Path Gambar",
    },
    lokasi: {
      province: "Provinsi",
      city: "Kota",
      district: "Kecamatan",
      village: "Desa/Kelurahan",
      rt: "RT",
      rw: "RW",
      toponimi: "Toponimi",
      latBgn: "Latitude Bangunan",
      longBgn: "Longitude Bangunan",
    },
    bangunan: {
      buildingConstruction: "Konstruksi Bangunan",
      buildingFloorType: "Jenis Lantai",
      buildingType: "Tipe Bangunan",
      buildingWall: "Dinding Bangunan",
      roofType: "Jenis Atap",
      floorCount: "Jumlah Lantai",
      luasBgn: "Luas Bangunan (m²)",
      luasBgnBaru: "Luas Bangunan Baru (m²)",
      luasBgnLama: "Luas Bangunan Lama (m²)",
      electricity: "Daya Listrik (VA)",
    },
  },
};
