export default {
  table_vectors: {
    headers: [
      { title: "No", key: "no" },
      { title: "Name", key: "name" },
      { title: "Type", key: "type" },
      { title: "Category", key: "category" },
      { title: "Status", key: "isActive" },
      { title: "Created At", key: "updatedAt" },
      { title: "Updated At", key: "createdAt" },
      { title: "Actions", key: "action" },
    ],
  },

  table_data: {
    headers: [
      { title: "No", key: "no" },
      { title: "Province", key: "province" },
      { title: "City", key: "city" },
      { title: "Kecamatan", key: "district" },
      { title: "Kelurahan", key: "village" },
      { title: "Status", key: "status" },
      { title: "NOP", key: "taxObjectNumber" },
      { title: "NOP BARU", key: "newTaxObjectNumber" },
      { title: "Update", key: "buildingUpdate" },
      { title: "Actions", key: "action" },
    ],
  },
  land_parcel_table: {
    headers: [
      { title: "No", key: "no", sortable: false },
      { title: "NIB", key: "nib", sortable: false },
      {
        title: "Nama Pemilik",
        key: "taxPayerName",
        sortable: false,
        minWidth: "300px",
      },
      {
        title: "Jenis Hak",
        key: "typeOfRight",
        sortable: false,
        minWidth: "150px",
      },
      { title: "Luas Persil", key: "l_bumi", sortable: false },
      {
        title: "Alamat Objek Pajak",
        key: "taxObjectAddress",
        sortable: false,
        minWidth: "200px",
      },
      { title: "RT", key: "rt", sortable: false },
      { title: "STAWPOP", key: "staWpop", sortable: false, minWidth: "200px" },
      { title: "Kelurahan", key: "village", sortable: false },
      { title: "Image", key: "image", sortable: false, minWidth: "120px" },
      { title: "Nomor Objek Pajak", key: "taxObjectNumber", sortable: false },
      // { title: "UUID Persil", key: "fid", sortable: false },
      { title: "Actions", key: "action", sortable: false, minWidth: "150px" },
    ],
    detailBapenda: {
      taxObjectNumber: "Nomor Objek Pajak (NOP)",
      taxPayerName: "Nama Wajib Pajak",
      taxPayerAddress: "Alamat Wajib Pajak",
      taxPayerPhone: "Telepon Wajib Pajak",
      taxPayerCode: "Kode Wajib Pajak",
      taxStatus: "Status Pajak",
      status: "Status Survey",
      staWpop: "Status Pemanfaatan Objek Pajak",
      pemilikAktual: "Pemilik Saat Ini",
      pemilikSebelumnya: "Pemilik Sebelumnya",
      kerjaWp: "Pekerjaan Wajib Pajak",
      kerjaWp2: "Pekerjaan Wajib Pajak 2",
      vehicleTotal: "Jumlah Kendaraan",
      twoWheelVehicleTotal: "Motor (Unit)",
      fourWheelVehicleTotal: "Mobil (Unit)",
    },
    detailBpn: {
      nib: "Nomor Induk Bidang",
      nibel: "Nomor Identifikasi Bidang Elektronik",
      typeOfRight: "Jenis Hak",
      rightNumber: "Nomor Hak",
      l_bumi: "Luas Tanah (m²)",
      l_tertul: "Luas Tertulis (m²)",
      landType: "Jenis Tanah/Bangunan",
      landUsage: "Penggunaan Tanah",
      metodeUkur: "Metode Pengukuran",
      alatUkur: "Alat Pengukuran",
      suratUkur: "Nomor Surat Ukur",
      imageUrls: "Path Gambar",
    },

    identitasWp: {
      taxPayerName: "Nama Wajib Pajak",
      taxPayerAddress: "Alamat Wajib Pajak",
      taxPayerPhone: "Telepon Wajib Pajak",
      taxPayerCode: "Kode Wajib Pajak",
    },
    pajak: {
      taxObjectNumber: "Nomor Objek Pajak (NOP)",
      taxStatus: "Status Pajak",
      status: "Status Survey",
      staWpop: "Status Pemanfaatan Objek Pajak",
    },
    kepemilikan: {
      pemilikAktual: "Pemilik Saat Ini",
      pemilikSebelumnya: "Pemilik Sebelumnya",
    },
    pekerjaan: {
      kerjaWp: "Pekerjaan Wajib Pajak",
      kerjaWp2: "Pekerjaan Wajib Pajak 2",
    },
    kendaraan: {
      vehicleTotal: "Jumlah Kendaraan",
      twoWheelVehicleTotal: "Motor (Unit)",
      fourWheelVehicleTotal: "Mobil (Unit)",
    },
    identitasBidang: {
      nib: "Nomor Induk Bidang",
      nibel: "Nomor Identifikasi Bidang Elektronik",
      typeOfRight: "Jenis Hak",
      rightNumber: "Nomor Hak",
    },
    luas: {
      l_bumi: "Luas Tanah (m²)",
      l_tertul: "Luas Tertulis (m²)",
    },
    penggunaan: {
      landType: "Jenis Tanah/Bangunan",
      landUsage: "Penggunaan Tanah",
    },
    pengukuran: {
      metodeUkur: "Metode Pengukuran",
      alatUkur: "Alat Pengukuran",
      suratUkur: "Nomor Surat Ukur",
    },
  },

  table_collection: {
    headers: [
      { title: "No", key: "no" },
      //   { title: "UUID", key: "fid" },
      //   { title: "UUID_BGN", key: "uuid_bgn" },
      { title: "Province", key: "province" },
      { title: "City", key: "city" },
      { title: "Kecamatan", key: "district" },
      { title: "Kelurahan", key: "village", minWidth: "150px" },
      { title: "Status", key: "status" },
      {
        title: "Alamat Object Pajak",
        key: "taxObjectAddress",
        minWidth: "200px",
      },

      { title: "NIB", key: "nib" },
      { title: "Total Bangunan", key: "buildingTotal" },
      { title: "NOP", key: "taxObjectNumber" },
      { title: "NOP BARU", key: "newTaxObjectNumber" },
    ],
  },
  target: {
    bangunan: {
      boba: 4949,
      apiapi: 5496,
      loktuan: 5055,
    },
    bidang: {
      boba: 3121,
      apiapi: 5021,
      loktuan: 4963,
    },
  },
  actual: {
    bangunan: {
      boba: 4949,
      apiapi: 5626,
      loktuan: 5055,
    },
    bidang: {
      boba: 3222,
      apiapi: 5294,
      loktuan: 5171,
    },
  },
};
