export default {
  progressHeader: [
    { title: "Area ID", value: "bagi_18", align: "center" },
    { title: "Grid ID", value: "GRID", align: "center" },
    { title: "Task Status", value: "status", align: "center" },
    { title: "Asignee", value: "asignee", align: "center" },
    // {
    //   title: "Digitasi",
    //   align: "center",
    //   children: [
    //     { title: "Bangunan", value: "digitasi_bangunan" },
    //     { title: "Transportasi", value: "digitasi_transportasi" },
    //     { title: "Badan Air", value: "digitasi_badan_air" },
    //     { title: "Penutupan Lahan", value: "digitasi_penutupan_lahan" },
    //     { title: "Digitasi Relief", value: "digitasi_relief" },
    //     { title: "Batas Administrasi", value: "digitasi_batas_administrasi" },
    //     { title: "Toponomi", value: "digitasi_toponomi" },
    //   ],
    // },
    { title: "Action", value: "action" },
  ],
  areaColors: {
    1: "rgba(255, 99, 132, 1)",
    2: "rgba(204, 65, 67, 1)",
    3: "rgba(255, 206, 86, 1)",
    4: "rgba(75, 0, 130, 1)",
    5: "rgba(153, 102, 255, 1)",
    6: "rgba(117, 57, 35, 1)",
    7: "rgba(201, 203, 207, 1)",
    8: "rgba(0, 128, 192, 1)",
    9: "rgba(128, 0, 64, 1)",
    10: "rgba(255, 0, 0, 1)",
    11: "rgba(128, 128, 0, 1)",
    12: "rgba(0, 0, 255, 1)",
    13: "rgba(146, 201, 255, 1)",
    14: "rgba(0, 255, 255, 1)",
    15: "rgba(255, 0, 255, 1)",
    16: "rgba(255, 128, 0, 1)",
    17: "rgba(64, 0, 128, 1)",
    18: "rgba(0, 64, 128, 1)",
  },
  statusGrid: {
    0: "To Do",
    1: "To Do Review",
    2: "Revision",
    3: "Done",
  },
  statusGridColor: {
    1: "info",
    2: "error",
    3: "success",
  },
  digitasiStatus: {
    0: "Tidak Ada",
    1: "Rejected",
    2: "Approved",
  },
  digitasiStatusColor: {
    1: "error",
    2: "success",
  },
  digitasiStatusIcon: {
    1: "mdi-close-circle",
    2: "mdi-checkbox-marked-circle",
  },
  digitasiItem: {
    digitasi_badan_air: "Badan Air",
    digitasi_bangunan: "Bangunan",
    digitasi_batas_administrasi: "Batas Administrasi",
    digitasi_penutupan_lahan: "Penutupan Lahan",
    digitasi_relief: "Relief",
    digitasi_toponomi: "Toponomi",
    digitasi_transportasi: "Transportasi",
  },
};
