export default {
  colorSchemeRdtr: {
    "Badan Jalan": "#1976D2",
    "Campuran Intensitas Tinggi": "#388E3C",
    IPAL: "#0288D1",
    IPAM: "#0097A7",
    "Kawasan Peruntukan Industri": "#00796B",
    Pariwisata: "#8BC34A",
    "Pembangkitan Tenaga Listrik": "#43A047",
    "Pengelolaan Persampahan": "#2E7D32",
    "Perdagangan dan Jasa Skala Kota": "#66BB6A",
    "Perdagangan dan Jasa Skala SWP": "#81C784",
    Pergudangan: "#4CAF50",
    Perkantoran: "#388E3C",
    "Perumahan Kepadatan Rendah": "#AED581",
    "Perumahan Kepadatan Sedang": "#9CCC65",
    "Perumahan Kepadatan Tinggi": "#7CB342",
    "SPU Skala Kecamatan": "#43A047",
    "SPU Skala Kelurahan": "#2E7D32",
    "SPU Skala Kota": "#1B5E20",
    Transportasi: "#009688",
    "Hutan Produksi yang dapat Dikonversi": "#F9A825",
    Pemakaman: "#FDD835",
    "Perikanan Budi Daya": "#FFB300",
    "Perikanan Tangkap": "#FFA000",
    "Tanaman Pangan": "#FBC02D",
    "Pertahanan dan Keamanan": "#B71C1C",
    "Badan Air": "#01579B",
    "Ekosistem Mangrove": "#004D40",
    "Hutan Lindung": "#1B5E20",
    "Jalur Hijau": "#2E7D32",
    "Perlindungan Setempat": "#33691E",
    "Rimba Kota": "#558B2F",
    "Taman Kecamatan": "#689F38",
    "Taman Kelurahan": "#8BC34A",
    "Taman Kota": "#43A047",
    "Taman Nasional": "#2E7D32",
    "Taman RT": "#9CCC65",
  },

  showedParcelAttribute: [
    {
      key: "KODEWILAYA",
      label: "Kode Wilayah",
      icon: "mdi-map-marker",
      iconColor: "blue",
    },
    {
      key: "NOMOR_HAK",
      label: "Nomor Hak",
      icon: "mdi-file-document-outline",
      iconColor: "indigo",
    },
    {
      key: "TIPEHAK",
      label: "Tipe Hak",
      icon: "mdi-file-certificate-outline",
      iconColor: "deep-purple",
    },
    {
      key: "NIB",
      label: "NIB",
      icon: "mdi-numeric",
      iconColor: "teal",
    },
    {
      key: "NAMA_WP",
      label: "Nama Wajib Pajak",
      icon: "mdi-account",
      iconColor: "green",
    },
    {
      key: "ALAMAT_WP",
      label: "Alamat Wajib Pajak",
      icon: "mdi-home-map-marker",
      iconColor: "orange",
    },
    {
      key: "ALAMAT_OP",
      label: "Alamat Objek Pajak",
      icon: "mdi-office-building-marker",
      iconColor: "amber",
    },
    {
      key: "KECAMATAN",
      label: "Kecamatan",
      icon: "mdi-map-search",
      iconColor: "cyan",
    },
    {
      key: "KELURAHAN",
      label: "Kelurahan",
      icon: "mdi-home-city",
      iconColor: "blue",
    },
    {
      key: "RT",
      label: "RT",
      icon: "mdi-numeric",
      iconColor: "pink",
    },
    {
      key: "LUASTERTUL",
      label: "Luas Tertulis",
      icon: "mdi-ruler-square",
      iconColor: "brown",
    },
    {
      key: "L_BUMI",
      label: "Luas Bumi",
      icon: "mdi-earth",
      iconColor: "red",
    },
  ],

  pbgAttribute: [
    {
      key: "SK_PBG",
      label: "Surat Keputusan PBG",
      icon: "mdi-file-certificate-outline",
      iconColor: "deep-purple",
    },
    {
      key: "NAMOBJ",
      label: "Nama Objek",
      icon: "mdi-home-city",
      iconColor: "teal",
    },
    {
      key: "PGN_LHN",
      label: "Penggunaan Lahan",
      icon: "mdi-map-outline",
      iconColor: "green",
    },
    {
      key: "PENGGUNAAN",
      label: "Penggunaan Bangunan",
      icon: "mdi-domain",
      iconColor: "orange",
    },
  ],
};
