export default {
  BindagTanahHeader: [
    { title: "FID", value: "FID" },
    { title: "ID", value: "ID" },
    { title: "Nama Kelurahan", value: "KELURAHAN" },
    { title: "Nama Kecamatan", value: "KECAMATAN" },
    { title: "Status", value: "status", sortable: true },
    { title: "Actions", value: "action" },
  ],
  statusMap: {
    ACCURATE: "Sudah Tepat",
    NEW_DATA: "Data Baru",
    TAX_OBJECT_MERGE: "Penggabungan Object Pajak",
    TAX_OBJECT_SPLIT: "Pemecahan Object Pajak",
    DELINEATION: "Delineasi",
    CONFLICT: "Sengketa",
    OWNER_CANNOT_BE_MEET: "Pemilik Tidak Bisa Ditemui",
    NOT_YET_SURVEYED: "Belum Disurvey",
    OTHER: "Sudah Tepat",
  },
  statusColorMap: {
    ACCURATE: "#008000",
    NEW_DATA: "#FFD700",
    TAX_OBJECT_MERGE: "#FFA500",
    TAX_OBJECT_SPLIT: "#FF8C00",
    DELINEATION: "#FF4500",
    CONFLICT: "#B22222",
    OWNER_CANNOT_BE_MEET: "#FF8C00",
    NOT_YET_SURVEYED: "#FF4500",
    OTHER: "#008000",
  },
  statusFeatureOptions: [
    { title: "Sudah Tepat", value: "ACCURATE" },
    { title: "Data Baru", value: "NEW_DATA" },
    { title: "Penggabungan Object Pajak", value: "TAX_OBJECT_MERGE" },
    { title: "Pemecahan Object Pajak", value: "TAX_OBJECT_SPLIT" },
    { title: "Delineasi", value: "DELINEATION" },
    { title: "Sengketa", value: "CONFLICT" },
    { title: "Pemilik Tidak Bisa Ditemui", value: "OWNER_CANNOT_BE_MEET" },
    { title: "Belum Disurvey", value: "NOT_YET_SURVEYED" },
    { title: "Lainnya...", value: "OTHER" },
  ],
  ownerTypeMap: {
    PUBLIC_FACILITY: "Fasilitas Umum",
    GOVERNMENT_AREA: "Government Area",
  },
  ownerTypeOptions: [
    { title: "Fasilitas Umum", value: "PUBLIC_FACILITY" },
    { title: "Government Area", value: "GOVERNMENT_AREA" },
  ],
};
