export default {
  pj_user: [
    "hyatma.a.a@mail.ugm.ac.id",
    "fikrikrz88@gmail.com",
    "kinanthinastiti@gmail.com",
    "prasetyarini.ea@gmail.com",
  ],
  stakeHolder_user: [
    "syahruddin@bontang.com",
    "syafrudin@bontang.com",
    "syafriansyah@bontang.com",
    "giri@bontang.com",
    "heru@bontang.com",
    "ruli@bontang.com",
    "yuli@bontang.com",
    "trias@bontang.com",
    "bambang@bontang.com",
    "purnama@bontang.com",
  ],
  superadmin_user: [
    "superadmin@gmail.com",
    "bontangsyafrudin@gmail.com",
    "bontanggiri@gmail.com",
    "bontangheru@gmail.com",
    "bontangsyafriansyah@gmail.com",
    "bontangjaya@gmail.com",
    "digitaltwinugm@gmail.com",
    "ugmruli@gmail.com",
    "ugmyuli@gmail.com",
    "ugmtrias@gmail.com",
    "ugmbambang@gmail.com",
    "ugmpurnama@gmail.com",
    "dhiasdmn@gmail.com",
  ],
  employee_user: [
    "lirifaasmarani@gmail.com",
    "anisaputri1006@gmail.com",
    "angsokanovita@gmail.com",
    "safiraardelia25@gmail.com",
    "indahfitriyaa11@gmail.com",
    "yeniikawati99@gmail.com",
    "annisa.rizky.kusuma04@gmail.com",
    "shintapuspam43@gmail.com",
    "devizulfa77@gmail.com",
    "99nabilla@gmail.com",
    "ainun.nisa.rezika@mail.ugm.ac.id",
    "endangretnonurhayati@gmail.com",
    "suzitessa99@gmail.com",
    "zaldywegy@gmail.com",
    "chrisyal9@gmail.com",
    "farryhandika.n79@gmail.com",
    "prabarian09@gmail.com",
    "michaelkrisna1975@mail.ugm.ac.id",
    "lkyudhistira@mail.ugm.ac.id",
    "test1@gmail.com",
  ],
  masterWebUser: ["dhiasdmn@gmail.com"],
};
