declare interface IGetLotSurveyParams extends IMinimalFilter {
  category: string;
  village?: string;
  staWpop?: string;
  landType?: string;
  rt?: string | number;
  typeOfRight?: string;
}
declare interface ILotSurveyItems {
  alatUkur: string | null;
  area: number;
  buildingFloorTotal: number | null;
  buildingTotal: number;
  citizenId: string;
  city: string;
  createdAt: string; // ISO date string
  district: string;
  fid: string;
  fourWheelVehicleTotal: number;
  id: string;
  imageUrls: string[];
  kerjaWp: string;
  kerjaWp2: string;
  ketSrtf: string;
  kw: string | null;
  l_bumi: string;
  l_tertul: string;
  landType: string;
  landUsage: string;
  latitude: string;
  longitude: string;
  metodeUkur: string | null;
  newTaxObjectNumber: string;
  newUuid: string;
  nib: string;
  nibel: string;
  ownerType: string;
  pemilikAktual: string;
  pemilikSebelumnya: string;
  phoneNumber1: string | null;
  phoneNumber2: string;
  polygonId: string;
  productType: string;
  produk: string | null;
  province: string;
  regionCode: string;
  rightNumber: string;
  rt: string;
  rw: string;
  staWpop: string;
  status: string;
  suratUkur: string | null;
  taxObjectAddress: string;
  taxObjectCode_1: string;
  taxObjectCode_2: string | null;
  taxObjectNumber: string;
  taxPayerAddress: string;
  taxPayerCode: string;
  taxPayerName: string;
  taxPayerPhone: string | null;
  taxStatus: string;
  twoWheelVehicleTotal: number;
  typeOfRight: string;
  updatedAt: string; // ISO date string
  uuid: string;
  validator: string | null;
  validator1: string | null;
  vehicleTotal: number | null;
  village: string;
  wallType: string | null;
  wwcCode: string;
  wwcPhoto: string | null;
  year: number;
}
